# TODO: Configure either containerd or docker as the container runtime
# TODO: containerd sudo containerd config default | sudo tee /etc/containerd/config.toml > /dev/null && sudo sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml
# TODO: docker setup equivalent to containerd steps WARN I found out this was in fact deprecated! :o
# DEBIAN MACHINES ONLY! NO UBUNTU!
- name: Set up Kubernetes control-plane
  hosts: master
  become: true

  tasks:
    - name: Add Kubernetes apt-key
      get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key
        dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
        mode: "0644"
        force: true
        
    - name: Install APT Transport HTTPS
      apt:
        name: apt-transport-https
        state: present

    - name: Add Kubernetes APT repository
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /"
        state: present
        update_cache: yes

    - name: Update package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install containerd
      apt:
        name: containerd.io
        state: latest
        update_cache: yes
    - name: Configure modules for containerd
      blockinfile:
        path: /etc/modules-load.d/containerd.conf
        block: |
          overlay
          br_netfilter

    - name: Create an empty file for K8S sysctl parameters
      copy:
        content: ""
        dest: /etc/sysctl.d/99-kubernetes-cri.conf
        force: no

    - name: Configure sysctl parameters for K8S
      lineinfile:
        path: /etc/sysctl.d/99-kubernetes-cri.conf
        line: "{{ item }}"
      with_items:
        - "net.bridge.bridge-nf-call-iptables  = 1"
        - "net.ipv4.ip_forward                 = 1"
        - "net.bridge.bridge-nf-call-ip6tables = 1"

    - name: Apply sysctl parameters
      command: sysctl --system

    - name: Config containerd
      shell: sudo containerd config default | sudo tee /etc/containerd/config.toml > /dev/null && sudo sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml


    - name: Install kubeadm, kubelet, and kubectl with latest versions
      apt:
        name: ['kubeadm', 'kubelet', 'kubectl']
        state: latest
        update_cache: yes

    - name: Initialize Kubernetes cluster
      command: kubeadm init --pod-network-cidr=10.244.0.0/16
      register: kubeadm_output

    - name: Save the kubeadm join command for worker nodes
      set_fact:
        kubeadm_join_cmd: "{{ kubeadm_output.stdout_lines | select('search', 'kubeadm join') | list }}"